### ISSUE TITLE
[Question] Pass decoded JWT token as a parameter

### ISSUE THREAD

**Issue by femt0** [zalando/connexion#1104]
### Description
I'm using JWT security scheme and I can't find a way to pass the decoded token as a parameter of the API methods.
Is there a way to do that?

``` yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: api.decode_token

security:
 - bearerAuth: []  
```

### Additional info:
Python 3.7.4
Connexion 2.4.0
