### ISSUE TITLE
pythonic_params do not convert the parameter type

### ISSUE THREAD

**Issue by vmarkovtsev** [zalando/connexion#1116]
### Description

The parameter type is not converted if the parameter is renamed to become pythonic.

I have `pythonic_params=True` and the following spec:

```yaml
/reposet/{id}:
    delete:
      operationId: delete_reposet
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
```

This spec defines a single `integer` parameter in the path. 
There is the following controller:

```python
async def delete_reposet(request: web.Request, id_: int) -> web.Response:
    print(type(id_))
    return web.Response(status=200)
```

### Expected behavior

The controller prints `int` for each request.

### Actual behavior

The controller prints `str` for each request. In other words, the type is not converted. If I rename `id` to `id_` everywhere in the spec, the type is converted and the controller prints `int` as expected. If I remove `pythonic_params` and rename `id_` to `id` in the controller, it prints `int`, too.

### Steps to reproduce

(already covered by the description)

### Additional info:

Output of the commands:

- `python --version` `3.7.5`
- `pip show connexion | grep "^Version\:"` `2.4.0`
