### ISSUE TITLE
connexion is ignoring x-tokenInfoUrl or x-tokenInfoFunc when using openapi3.0

### ISSUE THREAD

**Issue by EricDales** [zalando/connexion#1145]
### Description
connexion is ignoring x-tokenInfoUrl or x-tokenInfoFunc when using openapi 3.0 spec

### Expected behaviour
I want to apply a client credential security scheme. connexion should use x-tokenInfoUrl or x-tokenInfoFunc to verify the token. 
Here is the spec:
```
components:
  securitySchemes:
    myoauthprovider:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "{{accesstoken_url}}"
          x-tokenInfoUrl: "{{tokeninfo_url}}"
          scopes:
            openid: Openid scope
            profile: Profile scope
```
### Actual behaviour
Wether x-tokenInfoUrl or x-tokenInfoFunc is used, connexion is starting with message:
```
... x-tokenInfoFunc missing
... x-tokenInfoFunc missing
... x-tokenInfoFunc missing
... x-tokenInfoFunc missing
... x-tokenInfoFunc missing
```
Any attempt to request the api with a valid token is rejected with a 401. 
```
{
  "detail": "No authorization token provided",
  "status": 401,
  "title": "Unauthorized",
  "type": "about:blank"
}
```

### Additional info:

Output of the commands:

- `python --version`
```
$ python --version
Python 3.7.3
```

- `pip show connexion | grep "^Version\:"`
```
$ pip show connexion | grep "^Version\:"
Version: 2.5.0
```

**Comment by EricDales** [comment]
My bad, it's a dummy ssl cert verification issue ... Setting REQUEST_CA_BUNDLE fixes the problem. Is there another and more pythonic way to tell connexion to use a given CA cert ?

**Comment by EricDales** [comment]
Weird: it's working on my windows development machine but it's failing on the linux deployment host ...

**Comment by EricDales** [comment]
Update: setting both REQUESTS_CA_BUNDLE and export TOKENINFO_URL is the fix.

**Comment by EricDales** [comment]
ok ... my bad ... again. x-tokenInfoUrl is not at the right level. Must be:
```
components:
  securitySchemes:
    myoauthprovider:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "{{accesstoken_url}}"
          scopes:
            openid: Openid scope
            profile: Profile scope
      x-tokenInfoUrl: "{{tokeninfo_url}}"
```
