### ISSUE TITLE
Servers value always turned into relative value

### ISSUE THREAD

**Issue by timeconsumer** [zalando/connexion#1174]
### Description
New to using connexion but...

Whenever I specify the ```servers``` attribute in my swagger.yaml file with values such as "http://locahost:8080/v1" or "http://example.com/v1" the server value is always replaced with one entry of "v1" when looking at the Swagger UI after running the app. Am I doing something wrong?

### Expected behaviour
servers value in openapi.json shows absolute url for the server

### Actual behaviour

servers value shows relative value ("/v1") as the only server entry

### Steps to reproduce

specify the servers value of 
```
servers:
  - url: "http://localhost:8080/v1"
```

and run the app. Look at the generated openapi.json file

### Additional info:

Output of the commands:

- `python --version`
Python 3.6.8
- `pip show connexion | grep "^Version\:"`
Version: 2.6.0

**Comment by ktarplee** [comment]
I see the same thing.  Furthermore:  if you specify something like
```yaml
servers:
  - url: https://{customerId}.saas-app.com:{port}/v2
    variables:
      customerId:
        default: demo
        description: Customer ID assigned by the service provider
      port:
        enum:
          - '443'
          - '8443'
        default: '443'
```
It also just turn it into "/v2".  I care about this because I want to be able to use a reverse proxy in front of the swagger UI and have the requests work properly as in the SaaS example [here](https://swagger.io/docs/specification/api-host-and-base-path/).
