### ISSUE TITLE
multipleOf schema validation fails

### ISSUE THREAD

**Issue by advance512** [zalando/connexion#1211]
### Description

We get the error:
```
ERROR in validation.validate_schema:228: http://172.17.0.15:5000/some_path validation error: 0.58 is not a multiple of 0.01

Failed validating 'multipleOf' in schema['properties']['some_items']['items']['properties']['amount']:
    {'format': 'double',
     'maximum': 1000000,
     'minimum': 0,
     'multipleOf': 0.01,
     'type': 'number'}

On instance['some_items'][8]['amount']:
    0.58
```

When the data contains 0.58 and the type validation includes: `multpleOf: 0.01`.

### Expected behaviour

0.58 is a multiple of 0.01 - `0.01 * 58 == 0.58`. I know that there's an issue with floating point division and multiplication (`0.58 / 0.01 == 57.99999999999999) but I expected multipleOf to work up to a certain epsilon, let's say 0.00001 (perhaps - user configurable).

### Actual behaviour

Since `round(0.58 / 0.01) - 0.58 / 0.01 != 0`, the validator fails.

### Steps to reproduce

Type definition:
```
  Item:
    type: object
    properties:
      amount:
        type: number
        format: double
        multipleOf: 0.01
        maximum: 1000000
        minimum: 0
```

return it from an API method with value 0.58, as an example.

### Additional info:

Output of the commands:

- `python --version` --> 3.8.2
- `pip show connexion | grep "^Version\:" --> 2.6.0`
