### ISSUE TITLE
Unable to run flask app because unexpected behavior when app is run through terminal command.

### ISSUE THREAD

**Issue by Abdullahabid3691** [zalando/connexion#1272]
### Description

**Scenario - 1**: If I launch my app through Pycharm run/debug tool **Everything works fine** (flask app runs including the API defination from my agreement_api/openapi/specification.yaml file).

**Scenario - 2** : But executing python agreement_api/app.py (the main script which contains the app instance) through terminal gives me an error while binding the specification.yaml API with my flask app. to be specific at `connexion_app.add_api("specification.yaml")`:

### Expected behaviour
The flask app should be up and running.

### Actual behaviour
app's server is unable to start because of error: 
`AttributeError: module 'agreement_api.controllers.agreement_controller' has no attribute 'read_agreements'`

### Steps to reproduce
see **`Scenario - 2`** section.

### Additional info:
Clearly the above error message tells me that the method "read_agreeements" doesn't exist but believe me it does (because Scenario #1 is working fine and there are no typos, etc) My directory structure is as follows:

Project

> agreement_api

> > controllers
> > > agreement_controller.py

> > models

> > openapi
> > > specification.yaml

> > app.py

> Dockerfile
>  Pipfile
> License
 > > ...

**agreement_controller.py**

```
....
def read_agreements():
    agreements = Agreement.query.order_by(Agreement.agreement_status).all()

    agreement_schema = AgreementSchema(many=True)
    return agreement_schema.dump(agreements), 200
....
```
**specification.yaml**
```
servers:
  - url: /api
paths:
  /agreement:
    get:
      tags:
        - Agreement
      summary: Read the list of agreements
      description: Read the list of agreements
      x-openapi-router-controller: agreement_api.controllers.agreement_controller
      operationId: read_agreements
```

**app.py**

```
_, connexion_app = create_app()

app = connexion_app.app  # Flask instance initialized by Connexion

DB = SQLAlchemy(app)
DB.create_all()

MA = Marshmallow(app)

connexion_app.add_api("specification.yaml")
```

I have tried setting **FLASK_APP** variable, but it didn't work.

pipenv with following dependencies:
**Flask==1.1.1**
**connexion==2.7.0**
**openapi: 3.0.1**

[complete error log here](https://github.com/zalando/connexion/files/5024323/error-log.txt)

The output of the commands:
- `python --version`: `Python 3.6.9`
