### ISSUE TITLE
Unspecified media/mime type

### ISSUE THREAD

**Issue by AlesKas** [zalando/connexion#1280]
### Description
When request comes to API, following warning is shown:
`/usr/local/lib/python3.6/site-packages/connexion/apis/flask_api.py:199: FutureWarning: Implicit (flask) JSON serialization will change in the next major version. This is triggered because a response body is being serialized as JSON even though the mimetype is not a JSON type. This will be replaced by something that is mimetype-specific and may raise an error instead of silently converting everything to JSON. Please make sure to specify media/mime types in your specs.`
With following response specification:
```
application/json:
    schema:
        type: object
        properties:
            success: { type: boolean, enum: [true, false] }
            msg: { type: string, example: 'Repo sync has started' }
 ```
And when I attached debbuger, response mimetype,  content_type, and headers were correctly set to application/json.
Also, `is_json` property was set to true.

Output of the commands:

- `python --version` 3.6
- `pip show connexion | grep "^Version\:"` 2.6.0
