### ISSUE TITLE
Connexion fails to communicate with keycloak for token generation 

### ISSUE THREAD

**Issue by amelroua** [zalando/connexion#1285]
### Description
connexion doesn't get  x-tokenInfoUrl with swagger 2.0

### Expected behaviour
Access to API
I want to apply a password security scheme while using keycloak for token generation. connexion should use x-tokenInfoUrl  to verify the token.
Here is the spec:
```
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        password:
          tokenUrl: http://localhost:8080/auth/realms/demo-realm/protocol/openid-connect/token
          x-tokenInfoUrl: http://localhost:8080/auth/realms/demo-realm/protocol/openid-connect/token/introspect
          scopes:
            openid: Openid scope
            profile: Profile scope
```

### Actual behaviour
Any attempt to request the api with a valid token is rejected with a 401.

```
{
  "detail": "No authorization token provided",
  "status": 401,
  "title": "Unauthorized",
  "type": "about:blank"
}
```

### Additional info:

Output of the commands:

- `python --version`  
Python 3.6.9

- `pip show connexion | grep "^Version\:"`
Version: 2.5.0
