### ISSUE TITLE
util.py throws AttributeError: __args__ when deserializing a nested object in a post body in python 3.9

### ISSUE THREAD

**Issue by benomalley25** [zalando/connexion#1393]
### Description
Using a swagger generated connexion server with a post body defined something like:

```
Value1:
  type: string
  description: "desc"
Value2:
  type: integer
  description: "desc"
AdditionalInfo:
  type: object
  additionalProperties: true
  description: "Additional information "
```

When sending requests with params in the "additionalInfo" object the library used the _deserialize function in util.py. For the "AdditionalInfo" object the function attemps to use the following block:

    elif type_util.is_generic(klass):
        if type_util.is_list(klass):
            return _deserialize_list(data, klass.__args__[0])
        if type_util.is_dict(klass):
            return _deserialize_dict(data, klass.__args__[1])

However in python 3.9 the expression klass.__args__[1] throws an attribute error

Was able to work around by using a slightly different definition of the form:

```
Value1:
  type: string
  description: "desc"
Value2:
  type: integer
  description: "desc"
AdditionalInfo:
   $ref: '#/components/schemas/AdditionalInfo'
```

As with this schema nothing is deserialized as a dict
