### ISSUE TITLE
[support] Wildcard path support?

### ISSUE THREAD

**Issue by julien-lecomte** [zalando/connexion#1397]
Is it possible to accept any path length ?
Something like

```
paths:
  /api/redirects/gitlab/pages/{path}/*: 
    get:
     # (...)
      parameters:
        - name: "path"                                                                                 
          in: path
          description: "Project path."     
          required: true
          schema:
            type: string
            minLength: 1
                                             
```

Where path could be "one" or "one/two/three" ? I get 404 errors when I try the latter.
