### ISSUE TITLE
Parameters named "class" (or other python reserved words) don't work, even with pythonic_params=True?

### ISSUE THREAD

**Issue by daisieh** [zalando/connexion#1424]
### Description

I have a test endpoint with a query param called `class`, like so:

```
    /test:
        get:
            operationId: "operations.test_this"
            parameters:
                - in: query
                  name: class
                  schema:
                      type: string
                - in: query
                  name: yoohoo
                  schema:
                      type: string
                - in: query
                  name: filter
                  schema:
                      type: string
```

and in the routing,

```
def test_this(class_="blank", yoohoo="dd", filter_="sdfsdfs"):
    response = locals()
    http_status_code = 200
    return response, http_status_code
```

### Expected behaviour

`curl "http://localhost:3333/htsget/v1/test?class=header&yoohoo=yoohoo&filter=dddd"` should result in:
```
{
  "class_": "header",
  "filter_": "dddd",
  "yoohoo": "yoohoo"
}
```

### Actual behaviour

It actually results in:
```
{
  "class_": "blank",
  "filter_": "dddd",
  "yoohoo": "yoohoo"
}
```

### Steps to reproduce
As above

### Additional info:

Output of the commands:

- `python --version`
-- `Python 3.7.12`

- `pip show connexion | grep "^Version\:"`
-- `Version: 2020.0.dev1`
