### ISSUE TITLE
Mock server correctly ignores operationId, but executes x-bearInfoFunc

### ISSUE THREAD

**Issue by matthewdeanmartin** [zalando/connexion#1446]
This is in regards to the [mock server](https://connexion.readthedocs.io/en/latest/cli.html?highlight=mock#running-a-mock-server).

I do have to have the service installed and importable, and the specific operations are ignored and not executed, as a mock should do. But the mock server wants me to have real authentication. If I comment out the x-bearInfoFunc, I get a "no auth token provided".

In other words, it appears I'd have to rip out all the references to auth endpoints. Is there a way to use an identical openapi.yml file with the mock server without removing all references to `security`?

```yaml
    /secret:
        get:
            summary: Return secret string
            operationId: service.get_secret
            security:
                -   jwt: [ 'secret' ]
components:
    securitySchemes:
        jwt:
            type: http
            scheme: bearer
            bearerFormat: JWT
            # x-bearerInfoFunc: service.decode_token
```
