### ISSUE TITLE
Add flag for validation disabling

### ISSUE THREAD

**Issue by cansik** [zalando/connexion#182]
In my swagger definition I have a lot of parameters which contain a valid datatype which then is needed for our automated query builder:

```yaml
  PropertyGroup:
    properties:
      time_start:
        description: Start time of flare
        type: string
        format: date-time

      nar:
        description: NOAA active region number
        type: number
        format: int32

      lat_hg:
        description: Stonyhurst heliographic latitude of event
        type: number
        format: int32
```

Now the problem we encounter is, that sometimes the validation of these types is not possible because we need for example **nullable types** as well.

So my question is, if it is possible to add an option which disables the validation or a method to provide an own validator class for some datatypes?
