### ISSUE TITLE
How to define nullable response attributes?

### ISSUE THREAD

**Issue by dfeinzeig** [zalando/connexion#226]
If I have the properties of a response defined as:

```
name:
  type: string
count:
  type: integer
  format: int32
description:
  type: string
```

and I want description to be nullable, that is, the values are a string or the non-string value null, how can I define that in my swagger spec?
