### ISSUE TITLE
Type coercion

### ISSUE THREAD

**Issue by rredkovich** [zalando/connexion#288]
### Description

In some cases front end could pass integer as strings (especially old legacy code and it's hard to quickly change that behaviour). 

Could type coercion be introduced to convert that values to correct type internally like [Cerberus](http://docs.python-cerberus.org/en/stable/) do?

``` python
"amount": {'type': 'float', 'coerce': float}
```

Example:

Swagger:

``` yaml
...
parameters:
      - name: "amount"
        in: "body"
        description: "amount of something"
        required: true
        type: "number"
        format: "float"
```

Input

``` python
{"amount": "103.25"}
```

Becomes

``` python
{"amount": 103.25}
```

Validation is passed
