### ISSUE TITLE
Support x-patternProperties

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando/connexion#339]
### Description

Would be nice to be able to define that. It is not currently supported by Swagger though.

### Expected bahaviour

Be able to define something like:
```yaml
  Labels:
    type: object
    description: |
      State of labels of a resource.
    x-patternProperties:
      "^[\\w_-]+$":
        type: string
        description: |
          Value of the tag.
    example:
      stage: prod
```

And Connexion would remove the `x-` from `x-patternProperties` property before validating the JSON schema.

### Actual behaviour

Everything under `x-patternProperties` is ignored.
