### ISSUE TITLE
[Question] Parameter type "body" crashes API

### ISSUE THREAD

**Issue by ernanirst** [zalando/connexion#362]
Currently all my API endpoint parameters are from the type "query", however, I would like to send the parameter in the body of a POST. So I tried:

```
paths:
  /login:
    post:
      tags: [WebApp]
      operationId: app.post_login
      summary: Authenticate an user
      parameters:
        - name: username
          in: body
```

Everytime I change the type from "query" to "body" the API crashes, showing this error:
```
swagger_spec_validator.common.SwaggerValidationError: {'name': 'username', 'in': 'body'} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['post']['properties']['parameters']['items']:
    {'oneOf': [{'$ref': '#/definitions/parameter'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/login']['post']['parameters'][0]:
    {'in': 'body', 'name': 'username'}
```

Isn't "body" not supported anymore? How to get parameters in the body of a POST?

**Comment by hjacobs** [comment]
That's expected behavior, you need to define a body schema. Example: https://github.com/hjacobs/connexion-example/blob/master/swagger.yaml#L58

**Comment by ernanirst** [comment]
Thanks for the reply @hjacobs, I saw this example before I ask this question but I don't get why I need to define a schema. I'd like to send a HTTP POST with a json on the body, and on this body will have the field "username", but the field username is a string, not a json schema. How should I declare this with swagger?

**Comment by hjacobs** [comment]
@ernanirst you simply define the schema as type object with a property `username`:

```yaml
- name: this_name_is_irrelevant
  in: body
  schema:
    type: object
    properties:
      username:
         type: string

**Comment by hjacobs** [comment]
You can also use a string as the body directly:

```yaml
- name: this_name_is_irrelevant
  in: body
  schema:
    type: string
```

Please note that you would need to add JSON quotes here:

```bash
curl -X POST -H 'Content-Type: application/json' -d '"a string"' http://localhost:8080/my-path
