### ISSUE TITLE
Add support for x-authentication-scheme and Bearer auth scheme in apiKey security definition

### ISSUE THREAD

**Issue by advance512** [zalando/connexion#389]
### Description

As seen in issue #124, many users require support for JWT, specifically using the Bearer authentication scheme. 

Using JWT seems like a very common scenario, as are various non-Basic authentication schemes that use the [`Bearer` authentication scheme](https://tools.ietf.org/html/rfc6750#section-2.1) as basis. 
A hackish solution was offered in that thread, but the resultant experience isn't very comfortable and requires you to edit the Connexion source files (hence it is a problem to be based on the latest version of connexion).

I suggest a vendor-specific setting, `x-authentication-scheme`, in the security definition might suffice:

```
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    x-authentication-scheme: Bearer
```

This will cause the API key set in the Authorize dialog to be treated as a JWT token, hence when it is part of a Authorization header the prefix "Bearer " will be appended.
