### ISSUE TITLE
Mock Server should build response from field's example in schema

### ISSUE THREAD

**Issue by samperd** [zalando/connexion#409]
### Description
on connexion release 1.0.129
Running on windows
Executing from GitBash

As a Connexion user or API developer
I want to run a mock server using data listed in swagger examples
So that I can quickly validate and troubleshoot the bahaviours of the API spec.

### Expected behaviour
I would expect to get the sample data defined in the
` responses: $ref: '#/definitions/Department'`
defined as:
```
Department:
    type: object
    required:
      - legal_title
      - department_type
    properties:
      id:
        type: string
        description: System identifier
        example: "1"
        readOnly: true
      legal_title:
        type: string
        description: Department legal title
        example: "Department of the Environment"
        minLength: 1
        maxLength: 100
.
.
.
```

### Actual behaviour
when I point my browser to: 
`http://localhost:5000/departments`
I get:
`No example response was defined.`

### Steps to reproduce
When I run a mock server as:
`$ connexion.exe run goc-od-api/swagger/swagger.yaml --mock=all -v`
I get:
`INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)`
and when I point my browser to: 
`http://localhost:5000/departments`
I get:
`No example response was defined.`

### Additional info:

Output of the commands:

- `python --version`
```
$ python --version
Python 3.5.2
```
- `pip show connexion | grep "^Version\:"`
```
$ pip show connexion | grep "^Version\:"
Version: 1.0.129
```

**Comment by rafaelcaricio** [comment]
@samperd Thank you for reporting this. But it is a known limitation of the current implementation of mock. As described in https://github.com/zalando/connexion/pull/302. Unfortunately, we never intended to have it working the way you expected.

Maybe you want to send a PR adding this support?

**Comment by samperd** [comment]
OK, 

I read "https://github.com/zalando/connexion/pull/302"

Maybe I am not understanding the issue or I described the issue incorrectly.

I will try to reframe the question.

While in MOCK mode and Given a request of: 
http://localhost:5000/departments

Am I supposed to get a response of:
```
{
"id": "1",
"legal_title:"Department of the Environment"
.
.
.
}
```

I am not quite sure where I am supposed to add examples to the response body if not in:

> properties

:
```
      id:
        type: string
        description: System identifier
        example: "1"
        readOnly: true
```

I am sure I am missing something. I am just not sure what.

**Comment by rafaelcaricio** [comment]
We return the "example" property. Please try like that:
```yaml
Department:
    type: object
    required:
      - legal_title
      - department_type
    properties:
      id:
        type: string
        description: System identifier
        readOnly: true
      legal_title:
        type: string
        description: Department legal title
        minLength: 1
        maxLength: 100
    example:
        id: "1"
        legal_title: "Department of the Environment"
        department_type: "foobar"
```
