### ISSUE TITLE
Handle colon in tags

### ISSUE THREAD

**Issue by ddxgz** [zalando/connexion#416]
### Description
The SwaggerHub editor shows no error when put a colon `:` in a tag, so the connexion server should be able to handle the colon in tags, like transform the `:` as `_` in the `operationId`.

```
  /user/{userId}/activities/calories/date/{baseDate}/{endDate}:
    get:
      tags:
      - "schema:calories"
```

### Expected behaviour
The `:` transformed into a `_` in the `operationId` in `swagger.yaml`.

```
  /user/{userId}/activities/calories/date/{baseDate}/{endDate}:
    get:
      tags:
      - "schema:calories"
      operationId: "controllers.schema_calories_controller.user_user_id_activities_calories_date_base_date_end_date_get"
```

### Actual behaviour
The `:` is still a `:` in the `operationId` in `swagger.yaml`, it causes "ImportError: No module named 'controllers.schema:calories_controller'".

```
  /user/{userId}/activities/calories/date/{baseDate}/{endDate}:
    get:
      tags:
      - "schema:calories"
      operationId: "controllers.schema:calories_controller.user_user_id_activities_calories_date_base_date_end_date_get"
```

### Steps to reproduce
1. Put a `:` in a tag in a API description on SwaggerHub
2. Download server `python-flask`
3. Start the server

### Additional info:

Output of the commands:

- `python --version`
Python 3.4.3
- `pip show connexion | grep "^Version\:"` 
Version: 1.1.5
