### ISSUE TITLE
x-nullable support in response body validation

### ISSUE THREAD

**Issue by podhmo** [zalando/connexion#439]
### Description

I want to x-nullable support in response body validation.

### Expected behaviour

supporting  response object incuding null value as property. such as this person schema.

```yaml
definitions:
   person:
     properties:
       name:
         type: string
       nickname:
         type: string
          x-nullable: true
```

### Actual behaviour

validation error (input data is null and schema has x-nullable=true).  connexion's x-nullable support is not comprehensive.

### Additional info:

supporting x-nullable with jsonschema library(used by connexion) is  like a below code.
https://gist.github.com/podhmo/2259fa63b58f6bbc26d618976b7662db
