### ISSUE TITLE
path formatted parameters

### ISSUE THREAD

**Issue by kcacciatore** [zalando/connexion#449]
### Description
Hi - I'm trying to build an api that allows extensions to be added to the API created. For example:

`/v1/service/{serviceid}/{extension}`

Where the method invoked would pass {extension} as the remainder of the URL as a parameter to the invoked code, allowing it to process that part of the URL. 

I understand and have tested in Flask something like this:
`@app.route('/myapp/<serviceId>/<path:extension>', methods = ['POST', 'GET'])`

When I post something like:
`/service/myservice/my/custom/extension`
and as expected get serviceId='myservice' as one parameter and the remainder of the url (e.g. 'my/custom/extension' ) as the value for extension. 

I built what I believe to be equivalent using OpenAPI:
```
paths:
  /service/{serviceid}/{extension}:
    post:
      tags:
      - "serviceextension"
      summary: "Extension endpoint for services""
      operationId: "my_extension_service_by_id"
      produces:
      - "application/json"
      parameters:
      - name: 'serviceid'
        in: path
        type: string
        required: true
      - name: 'extension'
        in: path
        type: string
        required: true
        format: path

```
### Expected behaviour

I expect when posting an URL:

`/service/myservice/my/custom/extension`

I would have the my_extension_service_by_id invoked with  serviceid='myservice' and extension='my/custom/extension'

### Actual behaviour

I get a 404 error

### Steps to reproduce

Create an API as above - I used http://editor.swagger.io/#/ and generated the server stubs using python-flask

### Additional info:
python --version
Python 3.6.0b2

pip show connexion | grep "^Version\:"
Version: 1.0.129
Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`
