### ISSUE TITLE
supporting multiple file upload

### ISSUE THREAD

**Issue by nils250492** [zalando/connexion#510]
### Description

When I define a swagger path like that one:

```
paths:
  /importer:
    post:
      operationId: api.importer.startImport
      description: |
        Start import process.
      consumes:
        - multipart/form-data
      parameters:
        - name: assets
          in: formData
          type: array
          items:
            type: string
            format: binary
```

I am not able to get the "array" of files defined under the name assets. 
Only the first file which is send by the name assets...

`def startImport(xml,importMeta,assets = None) -> object:
    print(assets)`
Result is : `<FileStorage: '25d' ('application/octet-stream')>`

### Expected behaviour

Array of Files should be accessible in the function.

### Actual behaviour

Only one file is send to the function

### Steps to reproduce
Sending 2 File with the key "assets" 

### Additional info:

Output of the commands:

Python 3.6.2
Connexion Version: 1.1.14
