### ISSUE TITLE
Add more parameter validation on type:array

### ISSUE THREAD

**Issue by chimeno** [zalando/connexion#514]
### Description
When using a parameter like:
````
  dow:
    name: dow
    description: An array of days of the week (0 - 6)
    in: query
    required: true
    type: array
    items:
      type: integer
      minimum: 0
      maximum: 6
      maxItems: 7
      minItems: 1
    collectionFormat: csv
````
Validation doesn't occur given the properties (minimum, maximum, maxItems, minItems) that are in the https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject

### Expected behaviour
Validation on that properties should exists

### Actual behaviour
Validation doesn't occur

### Additional info:

Output of the commands:

- `3-6-1`
- `connexion=1.1.15`
