### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by lucas03** [zalando/connexion#601]
I was looking for some examples for pagination implementation with connexion and did not find any. Is there a good practice or generic approach to pagination with connexion? If there is not, should there be or it is totally out of scope for what should be in connexion code/docs?

**Comment by dutradda** [comment]
hello @lucas03 

connexion just manage the open api specification layer, there's no definitions about the data pagination on open api specification. So, you can define your api pagination like it:

```yml
paths:
  /my-data:
    get:
      opertionId: myPackage.get_my_data
      parameters:
        - name: page
           in: query
           type: integer
           default: 1
```

but all the pagination logic will be implemented by you.
