### ISSUE TITLE
support Kerberos-authentication

### ISSUE THREAD

**Issue by WouterVH** [zalando/connexion#649]
It would be nice to have support for Kerberos, using a security-definition like

```
securityDefinitions:

    negotiateAuth:
        type: "http"
        name: "Negotiate"
        in: "header"
```

see discussion here:
https://github.com/OAI/OpenAPI-Specification/issues/451
