### ISSUE TITLE
[OAuth] Option to make scopes optionnal but at least one of them is ok (scopes or option)

### ISSUE THREAD

**Issue by Diliz** [zalando/connexion#650]
##### First, hello there!
________

### Context
Just a little question regarding this issue: https://github.com/zalando/connexion/issues/256
Which was fixed here: https://github.com/zalando/connexion/pull/257

I was actually looking for the actually patched functionnality, actually it is not possible to make a validation for at least one scope (like an or and not an and), let me explain better.

##### What I actually have:
- 3 scopes: read, write, delete
- one route can have multiple scopes, but I don't want my user to have all of them at once

So, I tried to put multiple scopes in one path, for a specific route, like this:

```yaml
securityDefinitions:
  oauth-implicit:
    ...
    scopes:
      read: "read"
      write: "write"
...
paths:
  /testing:
    get:
      security:
        oauth-implicit-read:
          - read
          - write
```

##### What is does:
- you need to have the scopes read and write together to access this scope

Since I want my user to have just one of them to access it, I had the choice to make a new route with separated scopes, which is making me duplicates my endpoints, which is not really what rest is for, since it will duplicate access to my ressources.

##### So, the solution I came with:
Even if it's not really good, was to make multiple securityDefinition with one scope for each (I know this is not beautiful, but hey, I'm doing what I can xD ):

```yaml

securityDefinitions:
  oauth-implicit-read:
    ...
    scopes:
      read: "read"
  oauth-implicit-write:
    ...
    scopes:
      write: "write"
...
paths:
  /testing:
    get:
      security:
        oauth-implicit-read:
          - read
        oauth-implicit-write:
          - write
```
##### What is does:
- you can access my route without a scope with this, you'll get a 200 (for example).
- my two scopes are optionnals now, not what's expected.
- if you have a bad scope you will have a 403 error like it should.

This is actually a bug for this part (as specified here https://github.com/zalando/connexion/issues/586), but I also think that it can be better to have the possibility to make an "or" instead of an "and" somehow while putting our security in our endpoint definition, which is better for rights readability on swagger-ui, one authentication to do, etc.

### Question:

Is there a possibility to make the older solution working again with a specific tag in our securityDefinition (I think it would be better if we can put it in the security tag in the endpoint definition to have better control for it but if you got a better solution in mind I'm ok too ;) )?

________

##### Thanks for reading, and thanks for your work, this is greatly appreciated :+1: 

Regards,
Diliz

PS: I'm looking to what is makable and will make a pull request if I come up with a good solution, this is not a breaking change since this will be an option to set if we want to have this usage of scopes.
