### ISSUE TITLE
[dev-2.0] Idea: deprecate base_path argument, rely on templating instead

### ISSUE THREAD

**Issue by dtkav** [zalando/connexion#702]
# Proposal
deprecate base_path argument, rely on templating instead

# Details
From #692 #698 the base_path argument is counter-intuitive because it modifies the spec (no other features do this).

A way to do this in a more general way is to rely on the existing templating functionality and the 'arguments' argument.

ex. someone would put in their swagger 2 spec:
```
basePath: {{ base_path }}
```
and then
```
app.add_api('swagger.yaml', arguments={"base_path": "/api/v1"})
```
I think this is much cleaner because the templating happens at spec load time.

# What problem are you solving?
Setting the base_path is complicated in OAS3 because of the `servers` block:
```
servers: 
- url: https://main.site.com/path1
  description: The main prod server
- url: https://other.site.com/path2
  description: The other prod server
```
If you set the base_path on the API, it isn't immediately clear what will happen. Should it replace just the path? Should it update both urls? Which server is connexion implementing? (right now we just pick the first one).
What happens if you don't have a servers block? How can we add a path to a nonexistent url?

_Originally posted by @dtkav in https://github.com/zalando/connexion/issues/692#issuecomment-425009032_
