### ISSUE TITLE
`object` and `x-nullable` don't mix

### ISSUE THREAD

**Issue by fwkz** [zalando/connexion#705]
### Description
sending `null` as `send_time_slot` raise an validation error.
```yml
  send_time_slot:
    type: object
    x-nullable: true
    required:
    - start
    - end
    properties:
      start:
        type: integer
        minimum: 0
        maximum: 24
      end:
        type: integer
        minimum: 0
        maximum: 24
```

### Expected behaviour
`x-nullable` should apply to `object`, sending `null` as `send_time_slot` should pass validation

### Actual behaviour
Sending `null` as `send_time_slot` raise an validation error.

### Additional info:
```
connexion==1.5.3
```
