### ISSUE TITLE
Dashes in a header parameter should not be replaced with underscores

### ISSUE THREAD

**Issue by dmitriyrepin** [zalando/connexion#731]
### Description
The Swagger 2.0 specification allow header parameters with dashes (e.g., X-Request-ID):
https://swagger.io/docs/specification/2-0/describing-parameters/
```
    get:
      summary: Checks if the server is alive.
      parameters:
        - in: header
          name: X-Request-ID
          type: string
          required: true
```
However, when I run the Connexion python-flask code generator, it replaces the dashes in the header parameter name with underscores (X_Request_ID):
```
    get:
      summary: "Checks if the server is alive."
      operationId: "status_get"
      parameters:
      - name: "X_Request_ID"
        in: "header"
        required: true
        type: "string"
```
### Expected behavior
The header parameters name should remain as specified in the original swagger schema

### Actual behavior
Dashes in the header parameters name are replaced with underscore.

### Steps to reproduce
1) Copy the schema fragment from the 
https://swagger.io/docs/specification/2-0/describing-parameters/
to the swagger editor
https://editor.swagger.io/
2) Generate python-flask code (Generate Server -> python-flask)
3) Download the python-flask-server-generated.zip file and unzip it.
Review python-flask-server\swagger_server\swagger\swagger.yaml
4) Observe that the header parameters name was changed.

### Additional info:
Output of the commands: 
- `python --version`
- `pip show connexion | grep "^Version\:"`

N/A - the https://editor.swagger.io/ was used
