### ISSUE TITLE
[aiohttp] Unsupported http authorization scheme bearer

### ISSUE THREAD

**Issue by pando85** [zalando/connexion#822]
### Description
`Unsupported http authorization scheme bearer` when using `AioHttpApp`

### Expected behaviour
Not error message.

### Actual behaviour
Error `Unsupported http authorization scheme bearer`

### Steps to reproduce
Define jwt in openapi scheme.
```yaml
      security:
      - jwt: ['secret']

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: app.decode_token
```

### Additional info:

Output of the commands:

- `python --version`

```bash
$python --version
Python 3.7.1
```
- `pip show connexion | grep "^Version\:"`

```bash
$pip show connexion | grep "^Version\:"
Version: 2018.0.dev1
```
