### ISSUE TITLE
Auth scopes working only for OAuth

### ISSUE THREAD

**Issue by janbalaz** [zalando/connexion#863]
### Description
Scopes for other auths, e.g. BasicAuth are not passed from schema to auth function, `required_scopes` are always `None`.

### Expected behaviour
Filling out scopes in schema should get these to the auth function, even if it's not `OAuth`.
```
- security:
    - BasicAuth: [read, write]
```
It is expected to receive in auth function `["read", "write"]`

### Actual behaviour
`None` is received.

### Additional info:
Problem is in `security_decorator()` at `secure.py`, where `required_scopes` are set to `None` at the beginning, but only filled is auth is `OAuth`. I actually believe this is known of as I found in some PDF documentation of yours that OAuth should be specified ant then its scopes are passed even when BasicAuth is used. That is in my opinion bad design, because it forces me to specify OAuth in schema even though I don't plan to support it. Use case for scopes in BasicAuth still exists though. I noticed even OAuth-like exceptions are used no matter what type of auth is chosen. This does not look especially pretty or generic.
Place with potential bug: [secure.py](https://github.com/zalando/connexion/blob/master/connexion/operations/secure.py#L93)

Output of the commands:

- `python --version`
3.7.1
- `pip show connexion | grep "^Version\:"`
2.2.0

I can attempt  to push a fix if you want and I will add more information on how to reproduce and my workaround leveraging OAuth. There are also missing examples of other auth types with scopes.
Thank you for addressing this issue.

**Comment by chinmayprabhudesai** [comment]
By [OAS 3.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oauth-flow-object) definition scopes are only supported with `OAuth2`.

A related resource not exactly the spec but useful is [this](https://swagger.io/docs/specification/authentication/), which lists that scopes can be also used with `openID Connect Discovery`.

> Step 2. Applying security
For each scheme, you specify a list of security scopes required for API calls (see below). Scopes are used only for OAuth 2 and OpenID Connect Discovery; other security schemes use an empty array [] instead.

I would imagine `connexion` to follow the same!

**Comment by janbalaz** [comment]
@chinmayprabhudesai thanks, that would explain why there are no scopes examples for other auth types than OAuth in Connexion or Swagger documentation.

In my opinion, it's a bit sad since I consider scopes to be a great feature which could be leveraged by other auths.

Anyway, if someone needs this to be working via a hackish solution, you can either patch [secure.py](https://github.com/zalando/connexion/blob/master/connexion/operations/secure.py#L93) (not recommended) or misuse OAuth2 in the following way:
```yaml
# in your schema.yml
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            read: Allow to read some resource
            write: Allow to write some resource
            some_other_scope: Allow something other
    BasicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: path.to.auth.handler.func
            
# in your schema.yml in some endpoint definition
paths:
  '/some-resource':
    get:
      security:
        - OAuth2: [read]
        - BasicAuth: []
```
The code above will leverage that `connexion` is passing `required_scopes` to auth handlers. Now it's up to you how you want to handle scopes, you can follow [connexion example](https://github.com/zalando/connexion/blob/master/examples/openapi3/basicauth/app.py), which is basically:
```python
from connexion.decorators.security import validate_scope
from connexion.exceptions import OAuthScopeProblem


def basic_auth(username, password, required_scopes=None):
    # do your auth thing and find out what scopes your user has
    user_scopes = ["read", "write"]    # example scopes
    
    if required_scopes is not None and not validate_scope(required_scopes, user_scopes):
        raise OAuthScopeProblem(
            description="Something about the user not having access to this action.",
            required_scopes=required_scopes,
            token_scopes=user_scopes,
        )
```
Price for the above solution is propagating OAuth2 in your schema as possible auth although you don't plan to implement it. Since I'm not specifying auth function for OAuth2, I'm getting warnings in console. This can be solved by creating a dummy function, which would always raise `Unauthorized` error. Not pretty.

**Comment by dtkav** [comment]
I agree per @chinmayprabhudesai 's comment, connexion implements the OpenAPI spec, so I don't think it makes sense to break from that standard to includes scopes in basic auth.

I'm happy to hear you found a way for your use case.

I'll close this ticket for now - feel free to reopen if you have more thoughts or comments.

**Comment by cziebuhr** [comment]
Have a look at https://github.com/zalando/connexion/blob/master/docs/security.rst#basic-authentication. Just also configure oauth.

**Comment by fsaintma** [comment]
Hi @dtkav, @cziebuhr 
I try to follow the [documentation](https://github.com/zalando/connexion/blob/master/docs/security.rst#basic-authentication) which specify that we can use Basic authentication and Oauth scopes authorization in the same time. I have just launched this connexion (v2.7.0) [basicauth example](https://github.com/zalando/connexion/tree/master/examples/openapi3/basicauth) without success. Indeed required_scopes is always None. So I was wondering if it's a regression bug or an error in the documentation? Thanks for your help.

**Comment by cziebuhr** [comment]
@fsaintma Can you post your spec?

**Comment by fsaintma** [comment]
Hi @cziebuhr,

Thanks for your answer

I tried with my own spec and after with the connexion basic auth example spec:

* https://github.com/zalando/connexion/blob/master/examples/openapi3/basicauth/openapi.yaml

I just add a print(required_scopes) in the basic_auth method of the app.py file and it's always None.

```
connexion/examples/openapi3/basicauth$ ./app.py
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
None
127.0.0.1 - - [21/Sep/2020 11:21:07] "GET /secret HTTP/1.1" 200 -
None
127.0.0.1 - - [21/Sep/2020 11:21:47] "GET /secret HTTP/1.1" 200 

connexion/examples/openapi3/basicauth$ curl -u foo:bar http://0.0.0.0:8080/secret
You are user1 and the secret is 'wbevuec'

connexion/examples/openapi3/basicauth$ curl -u admin:secret http://0.0.0.0:8080/secret
You are admin and the secret is 'wbevuec'
```

Best regards.

**Comment by cziebuhr** [comment]
What do you expect `required_scopes` to be if there are no scopes defined in the spec? You have to configure both, oauth and basic auth. Then you get the oauth scopes as `required_scopes` in the basic auth handler.

**Comment by fsaintma** [comment]
Hi @cziebuhr. Thanks for your answer and sorry for my late answer. 
This is an incomprehension on my part because in the default example of [basic auth](https://github.com/zalando/connexion/blob/master/examples/openapi3/basicauth/openapi.yaml) you can find a scope in  secret endpoint security definition (i.e. basic: ['secret']). I suggest removing it because it is useless in this example. 

I managed to configure the oauth scopes (i.e. only scopes) with basic authentication with the following configuration, if it helps :)  

Many thanks again for your help

```
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: path to info_from_basic function
    Oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: fake authorization url
          scopes:
            secret: Secret scope
      x-tokenInfoFunc: path to fake info_from_oauth2 function
      x-scopeValidateFunc: path to fake validate_scope_oauth2 function
```

**Comment by mattixpet** [comment]
The `jwt: ['secret']` is still in the jwt example confusing people like myself. Also, the [docs](https://connexion.readthedocs.io/en/2.14.1/security.html) say for Bearer authentication: "It uses the same semantics as for x-tokenInfoFunc, but the function accepts one parameter: token." However, this is wrong. The function also gets `required_scopes` just like Basic auth and Apikey auth. And it is always None.

However, if anyone like me wants to use scopes with JWT or Apikey authentication it is possible in a suboptimal way by just defining multiple security definitions for each variation of scopes you need. For example

```
    jwt_1:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: controller.jwt_1
    jwt_2:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: controller.jwt_2
```

and then in those functions define the scopes to be used for your auth function, e.g. 

```
def jwt_1(token, required_scope):
    required_scopes = ['scope1', 'scope2']
    #  Code to auth token and validate scopes

def jwt_2(token, required_scope):
    required_scopes = ['scope3']
    # Code to auth token and validate scopes
```

I haven't tried, but I assume in the OP's example, this would also have worked

```
components:
  securitySchemes:
    BasicAuthRead:
      type: http
      scheme: basic
      x-basicInfoFunc: path.to.auth.handler.read
    BasicAuthWrite:
      type: http
      scheme: basic
      x-basicInfoFunc: path.to.auth.handler.write
```
