### ISSUE TITLE
Add support for multiple implementations in operationId

### ISSUE THREAD

**Issue by valgog** [zalando/connexion#89]
To make it possible to use the same `swagger.yaml` file, make it possible to specify several operationId entry points. Like:

```YAML
operationId:
  connexion:
    app.get_users
  swagger1st:
    get_users
```

Or maybe even to somehow pin the project to enable not per-swagger-first-library, but per-project distinction.
