### ISSUE TITLE
Allow setting a different name for a URL parameter and its corresponding python variable

### ISSUE THREAD

**Issue by geajack** [zalando/connexion#929]
Suppose I want to implement an endpoint `/data?from=12&until=52` which accepts parameters `from` and `until` (specifying timestamps or something). The problem is that I can't do this because Connexion always uses the name of the query parameter as the name for the Python variable. It's a shame to couple these things together because there are restrictions on Python variable names that don't exist for query parameters - I can't have a Python variable called `from`.

What I would suggest is a solution like this:

```
/data:
    get:
      operationId: "controller.get_data"
      parameters:
      - name: from
        in: query
        x-parameter-name: start_time
        schema:
          type: integer
```
