### ISSUE TITLE
Complex validation for query parameters doesn't work

### ISSUE THREAD

**Issue by lovesuper** [zalando/connexion#932]
### Description
I have write come custom validator for UUID type validation, and declared following statements:
```
uid_path:
  description: Some unique identifier of some entity
  in: path
  name: uid_path
  required: true
  schema:
    format: x_uid
    type: string
```
### Expected behaviour

It would validate my path parameter, and deny such strings as "abcd"

### Actual behaviour

It wouldn't and such string as "abcd" will get to the View

### Steps to reproduce

Even following simple code doesn't work:
```
uid_path:
  description: Some unique identifier of some entity
  in: path
  name: uid_path
  required: true
  schema:
    enum: ["A", "B", "C", "D"]
    type: string
```
It allows ANY string to pass through . But not integer to be honest

### Additional info:

Output of the commands:

- `Python 3.7.3`
- `Version: 2018.0.dev1`
