### ISSUE TITLE
Query parameter objects are not 'exploded'

### ISSUE THREAD

**Issue by johannegger** [zalando/connexion#963]
### Description
Connexion does not respect the 'explode' feature for query parameters. As an example the query object from [this stackflow answer](https://stackoverflow.com/questions/38187187/use-object-type-query-param-in-swagger-documentation/38188832#51277233) can be used. 
 
### Expected behaviour
Connexion should parse and pass 3 query parameters in flat form. 
genre_id=1
author_id=1
title=foobar

### Actual behaviour
The endpoint returns 400 BAD REQUEST with body:
```
{
    "detail": "Extra query parameter(s) author_id, genre_id, title not in spec",
    "status": 400,
    "title": null,
    "type": "about:blank"
}
```

### Steps to reproduce
1) Create an openapi specification with a simple endpoint and this query parameter definition:
```
parameters:
  - in: query
    name: values
    schema:
      type: object
      properties:
        genre_id: 
          type: integer
        author_id:
          type: integer
        title:
          type: string
    style: form
    explode: true
```
2) Start the connexion server - with the default validators
3) Issue a request to the endpoint with this query: ```?genre_id=1&author_id=1&title=foobar```

### Additional info:
openapi version is "3.0.0"

Output of the commands:

- `python --version`
Python 3.6.8
- `pip show connexion | grep "^Version\:"`
Version: 2.2.0
