### ISSUE TITLE
objects with style: deepObject and explode: true are not supported

### ISSUE THREAD

**Issue by drummerwolli** [zalando/connexion#970]
### Description

https://swagger.io/docs/specification/serialization/#query defines possible serialization styles. Connexion is not supporting at least one of them (style: deepObject).

might be related to https://github.com/zalando/connexion/issues/963

### Expected behaviour

`/users?id[role]=admin&id[firstName]=Alex` would result in an object/dict named id and the value `{"role": "admin", "firstName": "Alex"}`

### Actual behaviour

when issuing `/users?id[role]=admin&id[firstName]=Alex` the id parameter is not passed to the function linked to that endpoint.

### Steps to reproduce

create an endpoint with the following parameter:

```
- name: id
  required: true
  in: query
  style: deepObject
  explode: true
  schema:
    type: object
    properties:
      bla:
        type: string
```

try to query that endpoint with the query parameter `?id[role]=admin&id[firstName]=Alex`. There will be no data passed to the function.

### Additional info:

Output of the commands:

- `python --version` : Python 3.6.7
- `pip show connexion | grep "^Version\:"` : 2.2.0

**Comment by Ishrock** [comment]
I have a similar issue.

```
  /offers:
    get:
      oeprationId: a.offers_handler
      parameters:
      - name: fields
        required: true
        in: query
        style: deepObject
        explode: true
        schema:
          type: object
          properties:
            offers:
              type: string

      responses:
        200:
          description: ok
```

returns a connexion error of:

`GET  http://localhost:8080/products/1.0/offers?fields[offers]=some_value`

```
{
    "detail": "Extra query parameter(s) fields[offers] not in spec",
    "status": 400,
    "title": null,
    "type": "about:blank"
}
```

Im looking forward to your pull request, and being able to use deepObjects 😇

**Comment by edupo** [comment]
I'm hitting this issue on 2.7.0 when generating the server stubs using `openapi-generator` I do:

```
curl -X GET "http://127.0.0.1:8080/api/v1/sample/search?filter[a]=5&filter[b]=6&limit=20" -H "accept: application/json"
```

And in the server side when I do `pprint(connexion.request.args` I get:

```
ImmutableMultiDict([('filter[a]', '5'), ('filter[b]', '6'), ('limit', '20')])
```

The property on the `yml` looks like

```
      name: filter
      in: query
      schema:
        type: object
      style: deepObject
      explode: false
      required: true
```

I saw the PR fixing this merged a while ago, so... What am I doing wrong?
