### ISSUE TITLE
Allow for optional operationId

### ISSUE THREAD

**Issue by fehguy** [zalando/connexion#98]
The swagger spec states that operationId is optional.  We should auto-generate one if it does not exist--there is a simple algorithm that can be used here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L1086-L1107

**Comment by hjacobs** [comment]
@fehguy what would be the use case for this? Without a proper operationId we cannot resolve to any Python function, i.e. it would be like "operation not implemented".

**Comment by fehguy** [comment]
The ideal behavior would be to send mock responses for inimplemented methods. This is how both the node and Java frameworks operate, and it has been extremely well received.

**Comment by valgog** [comment]
One could define some special function, that is used if operationId is not present, and it would default to returning "operation not implemented".

**Comment by kleijnweb** [comment]
@fehguy I strongly disagree. The ideal behavior would be provide a "sensible default", eg something matching the HTTP method (as an aside, you are referring to stubbing, not mocking).

**Comment by hjacobs** [comment]
@kleijnweb could you elaborate on your "sensible default" proposal? I also dislike implementing stubbing/mocking as default behavior -- "not implemented" responses look more like the way to go (if one would really want to start the server without an operationId mapping)

**Comment by valgog** [comment]
What speaks against returning "Not implemented" error on invocation and putting a WARNING in the logs during initialization for the methods without defined `operationId` ?

**Comment by kleijnweb** [comment]
@hjacobs, @valgog 

Well, that's not it being optional. That's deferring the handling of the fact that it is required. With a Swagger spec you know all the endpoints, and you can know in advance that the Operation does not resolve. As a dev (-opper) I'd rather know sooner than later.

As I said, a sensible default would be the method name. HTTP methods are perfectly good verbs to use as operation names.

Then you need to know which module to look in, which I figure can look like this:

```python
def detect_controller(self):

    operation_id = self.operation['operationId']

    # Since operationId should be a unique identifier, never combine it with x_router_controller
    # See https://github.com/apigee-127/swagger-tools/issues/221
    if operation_id:
        return operation_id

    x_router_controller = self.operation['x-swagger-router-controller']

    if x_router_controller:
        mod_name = x_router_controller
    else:
        mod_name = self.default_router_controller_name

    return mod_name + '.' + self.method
```

Where `default_router_controller_name` should be passed down from `connexxion.App`, defaulting to `import_name`.

**Comment by kleijnweb** [comment]
That's a bit rough, give me some time to cook up a PR.

**Comment by kleijnweb** [comment]
I kept the current behavior of appending `operationId` to `x-swagger-router-controller`, debatable but looks useful to me.

**Comment by kleijnweb** [comment]
Realizing this wont work when you have more than one endpoint using the same HTTP method. Unless you define an operationId for the overlap, like so:

```yaml
paths:
  /request:
    get:
      operationId: 'app.request_api.everything'
      responses:
        '200':
          description: EOK
    post:
      parameters:
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/Request'

  '/request/{id}':
    put:
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int64
        - in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/Request'
    copy:
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int64
    delete:
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int64
    get:
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int64
```
And of course wont work when dealing with multiple resource types, so pretty limited 'as is'.

**Comment by kleijnweb** [comment]
Addressed both issues in #107, example:

`app.py`:

```python
import connexion

app = connexion.App(__name__)
app.add_api('swagger.yaml', default_module_name='api')
application = app.app

if __name__ == '__main__':
    app.run(port=8880, server='gevent')
```

The `default_module_name` is now configurable per `Api` which makes more sense.

`api/foo.py`:
```python
from connexion import NoContent

def post(request):
    return 'the new foo'

def patch(id, bar):
    return 'the updated foo'

def put(id, bar):
    return 'the replacement foo'

def copy(id):
    return 'the bar foo'

def delete(id):
    return NoContent, 204

def get(id):
    return 'a single foo''

def search():
    return 'found foos''
```

`api/bar.py`:
```python
from connexion import NoContent

def post(request):
    return 'the new bar'

def patch(id, bar):
    return 'the updated bar'

def put(id, bar):
    return 'the replacement bar'

def copy(id):
    return 'the bar copy'

def delete(id):
    return NoContent, 204

def get(id):
    return 'a single bar''

def search():
    return 'found bars''
```

```yaml
paths:
  /:
    get:
       # Implied operationId: api.get
  /foo:
    get:
       # Implied operationId: api.foo.search
    post:
       # Implied operationId: api.foo.post

  '/foo/{id}':
    get:
       # Implied operationId: api.foo.get
    put:
       # Implied operationId: api.foo.post
    copy:
       # Implied operationId: api.foo.copy
    delete:
       # Implied operationId: api.foo.delete

  /bar:
    get:
       # Implied operationId: api.bar.search
    post:
       # Implied operationId: api.bar.post

  '/bar/{id}':
    get:
       # Implied operationId: api.bar.get
    put:
       # Implied operationId: api.bar.post
    copy:
       # Implied operationId: api.bar.copy
    delete:
       # Implied operationId: api.bar.delete
```
